version: '2'

services:
    data:
        image: debian:jessie
        volumes:
            - .:/app
        tty: true

    frontend:
        build: etc/docker/dev/frontend
        volumes_from:
            - data
        environment:
            NPM_CONFIG_PREFIX: /app/var/docker/dev/npm/prefix
            NPM_CONFIG_CACHE: /app/var/docker/dev/npm/cache

    db:
        extends:
            file: etc/docker/common/db/docker-compose.yml
            service: db
        volumes:
            - ./var/docker/dev/mysql:/var/lib/mysql

    app:
        build: etc/docker/dev/app
        volumes_from:
            - data
        links:
            - db
            - blackfire
        environment:
            HISTFILE: /app/var/docker/dev/.bash_history
            XDG_CONFIG_HOME: /app/var/docker/dev/.config # Required for PsySH
            COMPOSER_HOME: /app/var/docker/dev/composer

    web:
        build: etc/docker/dev/web
        ports:
            - 80
        links:
            - app
        volumes_from:
            - data
        volumes:
            - ./var/docker/dev/nginx:/var/log/nginx

    app_debug:
        build:
            context: etc/docker/dev/app
            args:
               USE_XDEBUG: "yes"
        volumes_from:
            - data
        links:
            - db
            - blackfire
        environment:
            HISTFILE: /app/var/docker/dev/.bash_history
            XDG_CONFIG_HOME: /app/var/docker/dev/.config # Required for PsySH
            COMPOSER_HOME: /app/var/docker/dev/composer

    web_debug:
        build: etc/docker/dev/web
        ports:
            - 80
        links:
            - app_debug:app
        volumes_from:
            - data
        volumes:
            - ./var/docker/dev/nginx:/var/log/nginx

    # Set your blackfire IDs and tokens as environment variables
    # on your system before building the containers.
    # You can find your IDs and tokens in your account profile
    # https://blackfire.io/account or on the blackfire docker
    # integration page: https://blackfire.io/docs/integrations/docker
    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
