imports:
    - { resource: sonata/admin.yml }
    - { resource: sonata/block.yml }
    - { resource: sonata/user.yml }
    - { resource: sonata/rest.yml }

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
