# FOS Rest Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        # Original value: force
        # See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1354
        view_response_listener: true
    body_converter:
        enabled: true
        validate: true
