---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Remove default nginx config
  file: path=/etc/nginx/sites-available/default state=absent
  notify: restart nginx

- name: Add php-fpm to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1 php-fpm' line='127.0.0.1 php-fpm' owner=root group=root mode=0644

- name: Change default nginx site
  template: src=../../../../../nginx/default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
